trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo k8s terraform azure
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publicKey
  inputs:
    secureFile: 'id_rsa.pub'
    retryCount: '5'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/Kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret'
    backendServiceArm: 'azure-resource-manager-service-manager'
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmStorageAccountName: 'k8sstorageaccountbilal'
    backendAzureRmContainerName: 'k8sstorageaccountcontainer'
    backendAzureRmKey: 'k8sstorageaccountcontainer''
    allowTelemetryCollection: true

  
