trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'AWS-Connection'
    backendAWSBucketName: 'terraform-backend-state-bilal'
    backendAWSKey: 'bilal514'
# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'aws'
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
#     environmentServiceNameAWS: 'AWS-Connection'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'AWS-Connection'